### ISSUE TITLE
Difference between Authorization and Signature not clear

### ISSUE THREAD

**Issue by bblfish** [w3c-ccg/http-signatures#13] opened 2017-08-01 21:04 UTC
I find that the use cases for `Signature: ...` are not as clear as those for the `Authorization: ...` header. 

[Section 3.1.1](https://w3c-dvcg.github.io/http-signatures/#rfc.section.3.1.1) shows clearly how `Authorization: Signature ...` headers are meant to follow on a `401` with a `WWW-Authenticate: Signature...` header.

What is less clear is what the `Signature: ...` header is for. Is that for a server to sign what it is sending a client? When would this way of doing things be better than using the `Authorization: Signature ...` if it were used by a client?

**Comment by msporny** [comment] 2017-08-01 21:11
> Is that for a server to sign what it is sending a client? 

Yep, you got it.

> When would this way of doing things be better than using the Authorization: Signature ... if it were used by a client?

Authorization is expected when a client is authenticating itself to a server. A server is not supposed to respond with an Authorization header, IIRC. That is, the Authorization header is purely meant for client to server communication. That said, I can't remember the RFC where I read that, most likely in the HTTP specs... and HTTP/2 might have changed that requirement (although, I doubt it).

**Comment by liamdennehy** [comment] 2018-08-27 18:40
* ``Authorization`` is used for a client to prove identity and authorisation to perform an action. A [bearer token](https://tools.ietf.org/html/rfc6750), APIKey, username/password or other secret is usually used to prove this. In this specification, we assert identity by demonstrating control of the private key (rsa/ec) or shared secret (hmac) used to generate the signature.
* ``Signature`` is used when the signer wants to make a non-identity claim (or augment it), including authenticity (it came from me, most strongly possible under rsa/ec), non-repudiation (it could only have come from the signer, who cannot deny it later, only applicable to rsa/ec) and integrity (it has not changed since the signature was generated, for hmac/rsa/ec).

Essentially ``Authorization`` is saying "I am a party, here is my proof, may I please have permission to do..." like showing a passport/driver's license or automated toll booth pass, while ``Signature`` is "I assert the contents signed are correct and generated by me" like signing a contract or proof of delivery - this may sometimes be *after* the counterparty checked your identity, but is not in itself confirmation *of* your identity.

**Comment by liamdennehy** [comment] 2018-11-21 17:58
@bblfish Can you take a look at the content of https://github.com/w3c-dvcg/http-signatures/pull/48 and see if it clarifies this?

**Comment by liamdennehy** [comment] 2019-05-20 12:59
@bblfish MR #48 specifically addresses this issue and has now been merged into the new draft v11, can you confirm the content matches your expectations?

**Comment by bblfish** [comment] 2019-05-20 13:09
ok, it looks like the signature part, given as it has to sign the hash of the whole message, is likely to be very fragile, since any change to the message however small would invalidate the signature.

**Comment by liamdennehy** [comment] 2019-05-20 15:43
> any change to the message however small would invalidate the signature.

By design, and is the basis for Digital Signature security.

However, this issue is about the unclear distinction between Authrization: Signature header and the Signature: header, which I hope has been clearly spelled out in the merge.

**Comment by liamdennehy** [comment] 2019-08-10 09:32
@bblfish, do the changes address your concerns? If so, can we close this issue?

**Comment by liamdennehy** [comment] 2019-08-22 10:11
PR #48 specifically addresses this issue.

**Closed as completed by liamdennehy** 2019-08-22 10:11 UTC
Labels: quality

**Comment by bblfish** [comment] 2019-09-04 09:05
It is difficult to say with so much time having gone by. I'd need to reimplement with the latest spec to refresh my memory. I trust you did a good job :-)
